AWSTemplateFormatVersion: '2010-09-09'

Description: Network infrastructure for Clinic Booking System

Parameters:

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC

Resources:

  ClinicVPC:
    Type: AWS::EC2::VPC

    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true

      Tags:
        - Key: Name
          Value: Clinic-Booking-VPC


  InternetGateway:
    Type: AWS::EC2::InternetGateway

    Properties:
      Tags:
        - Key: Name
          Value: Clinic-Booking-IGW


  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment

    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref ClinicVPC